/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojadeesportes;

import javax.swing.JOptionPane;

/**
 *
 * @author ALESSANDRA
 */
public class Tela_Cheque extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Cheque
     */
    public Tela_Cheque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelprecoCheque = new javax.swing.JLabel();
        jLabelnomeCheque = new javax.swing.JLabel();
        jLabelcidadeCheque = new javax.swing.JLabel();
        jLabeldataCheque = new javax.swing.JLabel();
        jTextFieldprecoCheque = new javax.swing.JTextField();
        jTextFieldnomeCheque = new javax.swing.JTextField();
        jTextFieldcidadeCheque = new javax.swing.JTextField();
        jTextFielddataCheque = new javax.swing.JTextField();
        jButtonpagamento = new javax.swing.JButton();
        jButtonsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelprecoCheque.setText("Preço do cheque (por extenso)");

        jLabelnomeCheque.setText("Nome:");

        jLabelcidadeCheque.setText("Cidade:");

        jLabeldataCheque.setText("Data:");

        jTextFieldprecoCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldprecoChequeActionPerformed(evt);
            }
        });

        jTextFieldnomeCheque.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jButtonpagamento.setText("Confirmar Pagamento");
        jButtonpagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpagamentoActionPerformed(evt);
            }
        });

        jButtonsair.setText("Sair");
        jButtonsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelprecoCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelnomeCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelcidadeCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabeldataCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldprecoCheque)
                        .addComponent(jTextFieldnomeCheque)
                        .addComponent(jTextFieldcidadeCheque)
                        .addComponent(jTextFielddataCheque, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonpagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonsair, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelprecoCheque)
                .addGap(11, 11, 11)
                .addComponent(jTextFieldprecoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelnomeCheque)
                .addGap(9, 9, 9)
                .addComponent(jTextFieldnomeCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelcidadeCheque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldcidadeCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeldataCheque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFielddataCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonpagamento)
                    .addComponent(jButtonsair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsairActionPerformed
        // TODO add your handling code here:
        Tela_Venda frame = new Tela_Venda();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonsairActionPerformed

    private void jTextFieldprecoChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldprecoChequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldprecoChequeActionPerformed

    private void jButtonpagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpagamentoActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTextFieldprecoCheque.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Preencha o valor do cheque!");
        } else if ("".equals(jTextFieldnomeCheque.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Preencha o seu nome no cheque!");
        } else if ("".equals(jTextFieldcidadeCheque.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Preencha a cidade!");
        } else if ("".equals(jTextFielddataCheque.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Preencha a data!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Pagamento Efetuado com sucesso");
        }
    }//GEN-LAST:event_jButtonpagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cheque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonpagamento;
    private javax.swing.JButton jButtonsair;
    private javax.swing.JLabel jLabelcidadeCheque;
    private javax.swing.JLabel jLabeldataCheque;
    private javax.swing.JLabel jLabelnomeCheque;
    private javax.swing.JLabel jLabelprecoCheque;
    private javax.swing.JTextField jTextFieldcidadeCheque;
    private javax.swing.JTextField jTextFielddataCheque;
    private javax.swing.JTextField jTextFieldnomeCheque;
    private javax.swing.JTextField jTextFieldprecoCheque;
    // End of variables declaration//GEN-END:variables
}
