/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojadeesportes;

import javax.swing.JOptionPane;

/**
 *
 * @author ALESSANDRA
 */
public class Tela_Dinheiro extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Dinheiro
     *
     */
    public Tela_Dinheiro() {
        initComponents();
    }

    public Tela_Dinheiro(String total) {
        initComponents();

        jTextFieldprecoProd.setText(total);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelprecoProd = new javax.swing.JLabel();
        jTextFieldprecoProd = new javax.swing.JTextField();
        jLabeldinheiro = new javax.swing.JLabel();
        jTextFielddinheiro = new javax.swing.JTextField();
        jLabeltroco = new javax.swing.JLabel();
        jTextFieldtroco = new javax.swing.JTextField();
        jButtonpagamento = new javax.swing.JButton();
        jButtonsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelprecoProd.setText("Valor total do(s) produto(s):");

        jTextFieldprecoProd.setEditable(false);
        jTextFieldprecoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldprecoProdActionPerformed(evt);
            }
        });

        jLabeldinheiro.setText("Dinheiro: ");

        jTextFielddinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddinheiroActionPerformed(evt);
            }
        });
        jTextFielddinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFielddinheiroKeyTyped(evt);
            }
        });

        jLabeltroco.setText("Troco:");

        jTextFieldtroco.setEditable(false);
        jTextFieldtroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtrocoActionPerformed(evt);
            }
        });

        jButtonpagamento.setText("Confirmar Pagamento");
        jButtonpagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpagamentoActionPerformed(evt);
            }
        });

        jButtonsair.setText("Sair");
        jButtonsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelprecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldprecoProd)
                        .addComponent(jLabeldinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addComponent(jTextFielddinheiro)
                        .addComponent(jLabeltroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldtroco))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonsair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonpagamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelprecoProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldprecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabeldinheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFielddinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabeltroco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldtroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButtonpagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonsair)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldprecoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldprecoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldprecoProdActionPerformed

    private void jTextFielddinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddinheiroActionPerformed

    private void jButtonsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsairActionPerformed
        // TODO add your handling code here:
        Tela_Venda frame = new Tela_Venda();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonsairActionPerformed

    private void jButtonpagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpagamentoActionPerformed
        // TODO add your handling code here:
        float valor_produto = Float.parseFloat(jTextFieldprecoProd.getText());
        float valor_recebido = Float.parseFloat(jTextFielddinheiro.getText());
        
        if (valor_produto > valor_recebido) {
            JOptionPane.showMessageDialog(rootPane, "Você é pobre brow!");
        }
        else if ("".equals(jTextFielddinheiro.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Preencha o valor que você vai pagar!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Pagamento Efetuado com sucesso");
            float troco = valor_recebido - valor_produto;
            String s = "" + troco;
            jTextFieldtroco.setText(s);
        }
    }//GEN-LAST:event_jButtonpagamentoActionPerformed

    private void jTextFielddinheiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFielddinheiroKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c) && !evt.isAltDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFielddinheiroKeyTyped

    private void jTextFieldtrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtrocoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Dinheiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Dinheiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Dinheiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Dinheiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Dinheiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonpagamento;
    private javax.swing.JButton jButtonsair;
    private javax.swing.JLabel jLabeldinheiro;
    private javax.swing.JLabel jLabelprecoProd;
    private javax.swing.JLabel jLabeltroco;
    private javax.swing.JTextField jTextFielddinheiro;
    private javax.swing.JTextField jTextFieldprecoProd;
    private javax.swing.JTextField jTextFieldtroco;
    // End of variables declaration//GEN-END:variables
}
