/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojadeesportes;

import javax.swing.JOptionPane;

/**
 *
 * @author ALESSANDRA
 */
public class Tela_Cartao extends javax.swing.JFrame {

    String a = "";

    /**
     * Creates new form Tela_Cartao
     */
    public Tela_Cartao() {
        initComponents();
    }

    public Tela_Cartao(String total) {
        initComponents();

        float total_vezes = (float) (Float.parseFloat(total) / 1.0);
        String s = "" + total_vezes;
        jTextFieldvalorParcela.setText(s);
        a = "" + s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltitularCartao = new javax.swing.JLabel();
        jLabelnumCartao = new javax.swing.JLabel();
        jLabelbandeiraCartao = new javax.swing.JLabel();
        jLabelcodCartao = new javax.swing.JLabel();
        jLabelparcela = new javax.swing.JLabel();
        jComboBoxparcela = new javax.swing.JComboBox<>();
        jTextFieldtitularCartao = new javax.swing.JTextField();
        jTextFieldnumCartao = new javax.swing.JTextField();
        jTextFieldbandeiraCartao = new javax.swing.JTextField();
        jTextFieldcodCartao = new javax.swing.JTextField();
        jTextFieldvalorParcela = new javax.swing.JTextField();
        jButtonpagamento = new javax.swing.JButton();
        jButtonsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabeltitularCartao.setText("Titular do cartão:");

        jLabelnumCartao.setText("Número do cartão:");

        jLabelbandeiraCartao.setText("Bandeira");

        jLabelcodCartao.setText("Código de segurança do cartão:");

        jLabelparcela.setText("Parcelas:");

        jComboBoxparcela.setEditable(true);
        jComboBoxparcela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9", " 10", " 11", " 12" }));
        jComboBoxparcela.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxparcelaItemStateChanged(evt);
            }
        });

        jTextFieldtitularCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtitularCartaoActionPerformed(evt);
            }
        });

        jTextFieldnumCartao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldnumCartaoKeyTyped(evt);
            }
        });

        jTextFieldbandeiraCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbandeiraCartaoActionPerformed(evt);
            }
        });

        jTextFieldcodCartao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldcodCartaoKeyTyped(evt);
            }
        });

        jTextFieldvalorParcela.setEditable(false);
        jTextFieldvalorParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldvalorParcelaActionPerformed(evt);
            }
        });

        jButtonpagamento.setText("Confirmar Pagamento");
        jButtonpagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpagamentoActionPerformed(evt);
            }
        });

        jButtonsair.setText("Sair");
        jButtonsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabeltitularCartao, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(jLabelnumCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelbandeiraCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelcodCartao)
                        .addComponent(jTextFieldtitularCartao)
                        .addComponent(jTextFieldnumCartao)
                        .addComponent(jTextFieldbandeiraCartao))
                    .addComponent(jTextFieldcodCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonpagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonsair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldvalorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelparcela, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxparcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeltitularCartao)
                            .addComponent(jLabelparcela)
                            .addComponent(jComboBoxparcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldtitularCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldvalorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelnumCartao)
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldnumCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelbandeiraCartao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldbandeiraCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelcodCartao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldcodCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonpagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonsair)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldbandeiraCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbandeiraCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldbandeiraCartaoActionPerformed

    private void jTextFieldvalorParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldvalorParcelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldvalorParcelaActionPerformed

    private void jButtonsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsairActionPerformed
        // TODO add your handling code here:
        Tela_Venda frame = new Tela_Venda();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonsairActionPerformed

    private void jTextFieldtitularCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtitularCartaoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldtitularCartaoActionPerformed

    private void jButtonpagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpagamentoActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTextFieldtitularCartao.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Preencha o titular do cartão!");
        } else if ("".equals(jTextFieldnumCartao.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Preencha o numero do cartão!");
        } else if ("".equals(jTextFieldbandeiraCartao.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Preencha a bandeira do cartão!");
        } else if ("".equals(jTextFieldcodCartao.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Preencha o código de segurança do cartão!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Pagamento Efetuado com sucesso");
        }
    }//GEN-LAST:event_jButtonpagamentoActionPerformed

    private void jTextFieldnumCartaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnumCartaoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c) && !evt.isAltDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldnumCartaoKeyTyped

    private void jTextFieldcodCartaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldcodCartaoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c) && !evt.isAltDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldcodCartaoKeyTyped

    private void jComboBoxparcelaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxparcelaItemStateChanged
        // TODO add your handling code here:
        Object o = jComboBoxparcela.getSelectedItem();
        float quantidade = Float.valueOf(o.toString());
        float total_vezes = (float) (Float.parseFloat(a) / quantidade);
        String parcela = "" + total_vezes;
        jTextFieldvalorParcela.setText(parcela);
    }//GEN-LAST:event_jComboBoxparcelaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cartao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonpagamento;
    private javax.swing.JButton jButtonsair;
    private javax.swing.JComboBox<String> jComboBoxparcela;
    private javax.swing.JLabel jLabelbandeiraCartao;
    private javax.swing.JLabel jLabelcodCartao;
    private javax.swing.JLabel jLabelnumCartao;
    private javax.swing.JLabel jLabelparcela;
    private javax.swing.JLabel jLabeltitularCartao;
    private javax.swing.JTextField jTextFieldbandeiraCartao;
    private javax.swing.JTextField jTextFieldcodCartao;
    private javax.swing.JTextField jTextFieldnumCartao;
    private javax.swing.JTextField jTextFieldtitularCartao;
    private javax.swing.JTextField jTextFieldvalorParcela;
    // End of variables declaration//GEN-END:variables
}
